project:
  type: website
  output-dir: docs
  preview:
    browser: true
    port: 5555
    watch-inputs: true
    navigate: true
  render:
    - "*-de.qmd"

website:
  title: "Satvik Raman"
  description: "Meine persönliche Webseite, um meine Interessen, Projekte und Erfolge zu präsentieren."
  site-url: "https://satvikraman.github.io"
  repo-url: "https://github.com/satvikraman/satvikraman.github.io"
  search: true
  back-to-top-navigation: true

  twitter-card:
    image: "/assets/profile/twitter_card.png"
    card-style: summary_large_image
    creator: "@satvikraman"
    site: "@satvikraman"
  
  open-graph:
    image: "/assets/profile/twitter_card.png"
    locale: de_DE  

  page-footer:
    left: |
      <span>{{< fa brands creative-commons >}} {{< var years >}} Satvik Raman · [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)</span>
    right: |
      <span>Built with [Quarto](https://quarto.org/) · [{{< fa brands github >}} Source]({{< var github-url >}})</span>

  navbar:
    pinned: true
    left:
      - text: "Über mich"
        href: index-de.html
      - text: "Projekte"
        file: projects/index-en.html

    right:
      - text: "{{< iconify bi globe2 size=1.1em title='Sprachen' >}}"
        aria-label: Sprachen
        menu:
          - text: English
            href: ../index-en.html
          - text: Deutsch
            href: ../index-de.html
      - text: "{{< iconify bi envelope size=1.1em title='E-mail' >}}"
        href: "mailto:satvikraman11@gmail.com"
      - text: "{{< iconify bi github size=1.1em title='GitHub' >}}"
        href: https://github.com/satvikraman
        rel: me
      - text: "{{< iconify bi linkedin size=1.1em title='LinkedIn' >}}"
        href: https://www.linkedin.com/in/satvik-raman-bb3841407
        rel: me

format:
  html:
    theme:
      - cosmo
      - /assets/theme.scss
    css: /assets/styles.css

lang: de-DE
language:
  ui: de
