---
title: "Subprime Crisis"
subtitle: ""
date: 2024-04-07
image: ""
twitter-card:
  image: ""
open-graph:
  image: ""
categories:
  - Finance
  - Leverage
blog-title-refs: 
  - "Collapse of Lehman Brothers"
concept-title-refs: 
  - "What are Prime, SubPrime and Alt-A loans"
  - "Mortgage vs Loans"
  - "Mortgage Backed Securities"
category-refs: ""  
---

We referred to the subprime crisis in the [Collapse of the Lehman Brothers](./../20240331/index.qmd) post. Lets dive deeper into the crisis itself here. 

The subprime crisis refers to the collapse of the US housing market in 2007-2008 that caused the failure of many financial institutions including investments banks, insurance companies and mortgage lenders. It was the onset of the Great Recession (2007-2009), thats regarded as the worst economic downturn since the Great Depression.

# Causes
## Lowering of Federal Interest Rates
US Federal reserve lowered interest rates to give a boost to the US economy after the dot-com bubble of 2000 and the 9/11 attacks in 2001. They reduced the interest rate 11 times from May 2000 and Dec 2001 [^1]. Interest rates were lowered from 6% in 2001 to about 1% in 2003 [^3] [^4]. Economic growth -> increased demand for homes -> mortgages. Drop in interest rates allowed them to lend to even subprime borrowers. The extent to which lending standards had been relaxed can be guaged by the fact that NINJA loans were also being offeredn

## Restructuring of banking loans
Changes in banking laws allowed banks to offfer loans to subprime customers with balloon payments or adjustable interest rates. Balloon payments: where large payments are intentionally shifted right towards the end of the loan period. Adjustable Rate Mortgages (ARMs): Rates that remained fixed and at relatively low leves for an initial period and then float a few percentage points higher with respect to the federal funds rate thereafter.

Until the housing prices were increasing, subprime borrowers were able to protect themselves by either refinancing, borrowing against the increased value of their homes or selling their homes at a profit and paying off their mortgages. In case of a default, the banks would reposses the property and sellt it for an amount more than the oirginal loan and hence book profits. SInce it seemed like a relatively safe way to make money, banks started aggressively marketing subprime loans. The share of subprime mortgages increased from about 2.5% to about 15% from 1990's to 2004-07.

## Securitization of mortgages
Further contributing to the growth of subprime mortgages was the practice of securitizating mortgages. Banks would bundle hundreds and thousands of subprime mortgages and sell them in the capital markets as securities (bonds). These bonds were known as Mortgage Back Securities (MBSs). The MBSs buyer was entitles a share of the interest and principal payments on the underlying loan. In some sense by selling MBSs, the banks were no longer lending money from their own reserves. Rather they acted as a broken between the borrower and the financial institutions buying the MBSs.

As home prices continued their meteoric rise through the early 2000s, MBSs became widely popular, and their prices in capital markets increased accordingly.

## Dilution of the net-capital requirement
In 2004, SEC reduced the net-capital requirement (the ratio of assets to debt financial institutions are required to maintain to safeguard from insolvency). This allowed financial instituions to make use of leverage to finance their shopping spree. 

# Keys Events Leading to the Crisis
## Rise in Federal Interest Rates
Beginning 2004 to 2006, the US Federal reserve raised the interest rates from 1.25% to 5.25%. This resulted in defaults from subprime borrowers holding ARMs. Since the housing bubble had reached a level of saturation the housing prices were no longer increasing as they did in the past. The subprime borrowers were unable to resort to the old trick of refinancing their loans, borrowing against the increased value of their hourse or selling their house for profits to repay their mortgages. As more and more subprime borrowers defaulted, the MBSs lost value resulting in a loss to the financial institutions holding them. These MBSs were bought and sold in countries outside of the US and hence the impact of this crisis spread globally. 

## Irony in the midst of the crisis
Rating agencies downgraded the same MBSs they had once initially given a 5 star rating.

# You might also like to read
```{python}
#| echo: false
#| output: asis

import sys
sys.path.insert(1, '../../pyfiles')
from ref import ref
ref()
```

[^1]: [Financial Crisis of 2007-08](https://www.britannica.com/money/financial-crisis-of-2007-2008){target="_blank"}
[^2]: [What was the Subprime Meltdown?](https://www.investopedia.com/terms/s/subprime-meltdown.asp){target="_blank"}
[^3]: [Federal Reserve: Open Market Operation](https://www.federalreserve.gov/monetarypolicy/openmarket.htm){target="_blank"}
[^4]: [Federal Reserve: Open Market Operation Archive](https://www.federalreserve.gov/monetarypolicy/openmarket_archive.htm){target="_blank"}