---
title: "Hedging"
subtitle: "<i>If you don't invest in risk management, it doesn't matter what business you are in, it's a risky business<br> - Gary Cohn</i>"
date: 2024-03-21
image: ""
twitter-card:
  image: ""
open-graph:
  image: ""
categories:
  - Finance
  - Leverage
---

# What is a Hedge?
Hedging is a risk management strategy that helps reduce the risk of loss from an existing position, if the price moves unfavourably. You can think of it as a form of insurance. However, unlike insurance where you a pay a premium to insure your property, hedging in the financial world involves trading in other securities to reduce the risk of unfavourable price movement. In more technical terms, to hedge, you trade in securities that are negatively correlated to the security whose position you are trying to hedge.

::: {.callout-caution collapse="true"}
## What is correlation?
Correlation is a derivative of the term "co-related". Any two things which are co-related to each other exhibit correlation. Correlation is measured as a coefficient, whose value ranges between -1 and 1. A value of -1 indicates, perfect negative correlation, which means if a price of a security moves up by "x%", the price of the other security would move down by the same "x%". Similarly a value of 1 indicates, perfect positive correlation, which means if a price of a security moves up by "x%", the price of the other security would also move up by the same "x%". Often the correlation coefficient would be in between -1 and 1.
:::

This post explains what hedging is with an example, rather than going into the different strategies available to hedge a position.

Lets work with an example. Assume you buy 100 stocks of a company "ABC" for $50 a share, thinking the price would go up in due course of time. To limit your losses from an adverse price movement, you buy a put option with a strike price of $40. 

::: {.callout-caution collapse="true"}
## What is put option?
The amount paid to buy the put option is called "premium". The put option provides you the right (not obligation) to sell the security at $40 on the day of maturity. Therefore, even if the price of the security falls below $40, you retain the right to sell it at $40. Conversely, if the price of the security goes above $40, you will do nothing. The amount lost in this case would be the premium amount you initially paid to buy the put option. 
:::

If the price of the security falls below $40, the initial buy position incurs more loss which is offseted by the gains of the bought put option. 

Conversely, if the price of the security moves above $40, the initial buy position gains value (losses reduce and the eventually turns into a gain once the price moves above $50) while the bought put option incurs a loss equal to the premium amount.

As the example above shows, a hedge, helps reduces the risk associated with a position. Firstly, it limits the amount of loss that can be incurred from a position. And because it reduces the risk of a position it also reduces the profit (in the example mentioned above, by an amount equal to the premium paid to buy the put option)

Hedging can also be done in the commodities market. For example, an airlines company might enter into a Futures contract to buy ATF at a fixed price (called the strike price) on a certain future date (called the expiry date). A futures contract obligates the buyer pay the strike price to buy the commodity. On the expiry date, even if the ATF is trading above the strike price, the airlines company will only pay the strike price to buy the quanta of ATF negotiated in the contract. On the flip side, even if the ATF is trading at a price below the strike price, the airlines company will need to pay the strike price to buy the ATF. Hedging via Futures helps a company budget future expenses and not be exposed to volatile price movements of a commodity. 

# Posts referencing this concept
[Financial Leverage](./../financial-leverage/index.qmd)

# Additional concepts you may be interested in
[Options]()
[Futures]()

# Further Reading & References
[Beginner's Guide to Hedging](https://www.investopedia.com/trading/hedging-beginners-guide/){target="_blank"}
